# Generated by Django 3.1.3 on 2020-11-26 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mumbai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoptions',
            name='airport',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainoptions',
            name='station',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
